version: 2

.tempates:
  .validate_template: &validate_template
    docker:
      -
        image: finalgene/hadolint:latest
    working_directory: /app
    steps:
      - checkout
      - setup_remote_docker
      -
        run:
          name: Validate Dockerfile
          command: |
            hadolint $VERSION/Dockerfile
  .build_template: &build_template
    docker:
      -
        image: docker:18.05.0-ce-git
    working_directory: ~/repo
    steps:
      - checkout
      - setup_remote_docker
      -
        run:
          name: Build application Docker image
          command: |
            docker build --tag php-cli:$VERSION $VERSION/
      -
        run:
          name: List created images
          command: |
            docker images

jobs:
  validate-5.3:
    environment:
      VERSION: "5.3"
    <<: *validate_template
  build-5.3:
    environment:
      VERSION: "5.3"
    <<: *build_template

  validate-5.4:
    environment:
      VERSION: "5.4"
    <<: *validate_template
  build-5.4:
    environment:
      VERSION: "5.4"
    <<: *build_template

  validate-5.5:
    environment:
      VERSION: "5.5"
    <<: *validate_template
  build-5.5:
    environment:
      VERSION: "5.5"
    <<: *build_template

  validate-5.6:
    environment:
      VERSION: "5.6"
    <<: *validate_template
  build-5.6:
    environment:
      VERSION: "5.6"
    <<: *build_template

  validate-7.0:
    environment:
      VERSION: "7.0"
    <<: *validate_template
  build-7.0:
    environment:
      VERSION: "7.0"
    <<: *build_template

  validate-7.1:
    environment:
      VERSION: "7.1"
    <<: *validate_template
  build-7.1:
    environment:
      VERSION: "7.1"
    <<: *build_template

  validate-7.2:
    environment:
      VERSION: "7.2"
    <<: *validate_template
  build-7.2:
    environment:
      VERSION: "7.2"
    <<: *build_template

  validate-7.3:
    environment:
      VERSION: "7.3"
    <<: *validate_template
  build-7.3:
    environment:
      VERSION: "7.3"
    <<: *build_template

workflows:
  version: 2
  validate_and_build:
    jobs:
      - validate-5.3
      - build-5.3:
          requires:
            - validate-5.3

      - validate-5.4
      - build-5.4:
          requires:
            - validate-5.4

      - validate-5.5
      - build-5.5:
          requires:
            - validate-5.5

      - validate-5.6
      - build-5.6:
          requires:
            - validate-5.6

      - validate-7.0
      - build-7.0:
          requires:
            - validate-7.0

      - validate-7.1
      - build-7.1:
          requires:
            - validate-7.1

      - validate-7.2
      - build-7.2:
          requires:
            - validate-7.2

      - validate-7.3
      - build-7.3:
          requires:
            - validate-7.3
